### ISSUE TITLE
Error coming while training ImportError: libcufft.so.11 

### ISSUE THREAD

**Issue by Abhijeet241093** [HRNet/Higher-HRNet-Human-Pose-Estimation#115]
Traceback (most recent call last):
  File "tools/dist_train.py", line 18, in <module>
    import torch
  File "hrnet/lib/python3.8/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcufft.so.11: cannot open shared object file: No such file or directory

**Comment by Abhijeet241093** [comment]
Error solved with cuda 12.4
