### ISSUE TITLE
I have a problem when working in WINDOW. 

### ISSUE THREAD

**Issue by Kijung-Kim** [HRNet/Higher-HRNet-Human-Pose-Estimation#20]
On Window,"torch.distributed.init_process_group" is not working  
so, I change this option.
_C.MULTIPROCESSING_DISTRIBUTED = False 

it Seemed to work fine.

But, After a few minutes ...
I got this problem

"RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward"

sometimes...words is change like this.

"RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'weight'"

**Comment by briliantnugraha** [comment]
Hi @Kijung-Kim , I also encountered similar issue as you.

The reason is because the value in args.gpu in dist_train.py contains value '0', which is accepted in Linux, but not in Windows.

You could define something like this in here: https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/tools/dist_train.py#L142
`args.gpu = 'cuda' # the value which is accepted in Windows, tested on Windows 10 with gtx1080`

**Comment by mslqing** [comment]
Hi @briliantnugraha, @Kijung-Kim. Have you ever encountered the following problems?
On Window,"torch.distributed.init_process_group" is not working
so, I change this option.
_C.MULTIPROCESSING_DISTRIBUTED = False

it Seemed to work fine.

But, After a few minutes ...
I got this problem

Traceback (most recent call last):
  File "tools/dist_train.py", line 319, in <module>
    main()
  File "tools/dist_train.py", line 114, in main
    args=(ngpus_per_node, args, final_output_dir, tb_log_dir)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\multiprocessing\spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\multiprocessing\spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\multiprocessing\spawn.py", line 19, in _wrap
    fn(i, *args)
  File "D:\mashenglei\code_msl\HigherHRNet-Human-Pose-Estimation-master\tools\dist_train.py", line 196, in main_worker
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\tensorboardX\writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\tensorboardX\pytorch_graph.py", line 235, in graph
    _optimize_trace(trace, torch.onnx.utils.OperatorExportTypes.ONNX)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\tensorboardX\pytorch_graph.py", line 175, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\tensorboardX\pytorch_graph.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\onnx\__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\onnx\utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\onnx\symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\onnx\symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "D:\mashenglei\anaconda3-msl\envs\pytorch-msl\lib\site-packages\torch\onnx\symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

**Comment by mslqing** [comment]
Hi @briliantnugraha, @Kijung-Kim. Have you ever encountered the following problems?
On Window,"torch.distributed.init_process_group" is not working
so, I change this option.
_C.MULTIPROCESSING_DISTRIBUTED = False
args.gpu = 'cuda'

it Seemed to work fine.

But, After a few minutes ...
I got this problem

Traceback (most recent call last):
  File "tools/dist_train.py", line 320, in <module>
    main()
  File "tools/dist_train.py", line 123, in main
    tb_log_dir
  File "tools/dist_train.py", line 228, in main_worker
    torch.cuda.set_device(args.gpu)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch\lib\site-packages\torch\cuda\__init__.py", line 279, in set_device
    device = _get_device_index(device)
  File "D:\mashenglei\anaconda3-msl\envs\pytorch\lib\site-packages\torch\cuda\_utils.py", line 34, in _get_device_index
    'or an integer, but got: '.format(device))
ValueError: Expected a cuda device with a specified index or an integer, but got:

**Comment by briliantnugraha** [comment]
Hi @mslqing , I've assumed that you want to do some training with HigherHRNet, then you encountered error with TensorboardX summary.
FYI, I have used a very simple way to solve this issue, it is by commenting the writer part. If you don't care (for now) with Tensorboard output, you could try the following:

**A. Set writer_dict = None on this line**
`https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/tools/dist_train.py#L183`

**B. Comment the other writer_dict**
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/tools/dist_train.py#L196
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/master/tools/dist_train.py#L315
https://github.com/HRNet/HigherHRNet-Human-Pose-Estimation/blob/b4610aecaa5cf3de3cd69bfb13c7c79c8d514c7c/lib/core/trainer.py#L99-L117

**C. Retry your training script with dist_train.py, it should be fine now :)**

**Comment by mslqing** [comment]
@briliantnugraha Hello, thank you for your answer. I modified the code according to your method, but got: "ValueError: Expected a cuda device with a specified index or an integer, but got:" error.

Traceback (most recent call last):
File "tools/dist_train.py", line 320, in
main()
File "tools/dist_train.py", line 123, in main
tb_log_dir
File "tools/dist_train.py", line 228, in main_worker
torch.cuda.set_device(args.gpu)
File "D:\mashenglei\anaconda3-msl\envs\pytorch\lib\site-packages\torch\cuda_init_.py", line 279, in set_device
device = _get_device_index(device)
File "D:\mashenglei\anaconda3-msl\envs\pytorch\lib\site-packages\torch\cuda_utils.py", line 34, in _get_device_index
'or an integer, but got: '.format(device))
ValueError: Expected a cuda device with a specified index or an integer, but got:
