### ISSUE TITLE
Failed to load model by Unpickling Error:invalid load key, '<'.

### ISSUE THREAD

**Issue by gnoilednad** [HRNet/Higher-HRNet-Human-Pose-Estimation#21]
Thank you for your great work!
On Google Colaboratory, Model load is failed.
I use this model  'pose_higher_hrnet_w32_512.pth'(Get from Google Drive https://drive.google.com/open?id=1V9Iz0ZYy9m8VeaspfKECDW0NKlGsYmO1).
I did not modify the code.

How do i fix this error?

command
```
!python tools/valid.py \
    --cfg experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml \
    TEST.MODEL_FILE models/pytorch/pose_coco/pose_higher_hrnet_w32_512.pth
```

log

```
=> creating output/coco_kpt/pose_higher_hrnet/w32_512_adam_lr1e-3
=> creating log/coco_kpt/pose_higher_hrnet/w32_512_adam_lr1e-3_2020-02-16-07-57
Namespace(cfg='experiments/coco/higher_hrnet/w32_512_adam_lr1e-3.yaml', opts=['TEST.MODEL_FILE', 'models/pytorch/pose_coco/pose_higher_hrnet_w32_512.pth'])
AUTO_RESUME: True
CUDNN:
(...)
Model Summary
Name                      Input Size                Output Size               Parameters                Multiply Adds (Flops)     
----------------------------------------------------------------------------------------------------------------------------------
Conv2d_1                  [1, 3, 512, 512]          [1, 64, 256, 256]         1728                      113246208                 
(...)
----------------------------------------------------------------------------------------------------------------------------------
Conv2d_302                [1, 32, 256, 256]         [1, 17, 256, 256]         561                       35651584                  
----------------------------------------------------------------------------------------------------------------------------------

Total Parameters: 28,645,331
----------------------------------------------------------------------------------------------------------------------------------
Total Multiply Adds (For Convolution and Linear Layers only): 47,864,348,672
----------------------------------------------------------------------------------------------------------------------------------
Number of Layers
Conv2d : 302 layers   BatchNorm2d : 301 layers   ReLU : 270 layers   Bottleneck : 4 layers   BasicBlock : 108 layers   Upsample : 28 layers   HighResolutionModule : 8 layers   ConvTranspose2d : 1 layers   
=> loading model from models/pytorch/pose_coco/pose_higher_hrnet_w32_512.pth
Traceback (most recent call last):
  File "tools/valid.py", line 220, in <module>
    main()
  File "tools/valid.py", line 118, in main
    model.load_state_dict(torch.load(cfg.TEST.MODEL_FILE), strict=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by bowenc0221** [comment]
I didn't encounter this issue before.
Several issues might be helpful:
https://github.com/pytorch/pytorch/issues/16203
https://stackoverflow.com/questions/56391392/how-to-fix-pickle-unpicklingerror-invalid-load-key-error-in-pytorch

**Comment by gnoilednad** [comment]
Thank you for your reply!
Suggested link was very helpful.
Download failure was cause of this error.
wget failed to download huge file from Google drive.
